FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o worker ./cmd/worker

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/worker /app/worker

EXPOSE 8081

CMD ["/app/worker"]